services:
  - rabbitmq
  - redis-server
sudo: false
cache: bundler
language: ruby
rvm:
  - ruby-head
  - "2.4.1"
  - "2.3.4"
  - "2.2.7"
matrix:
  include:
    - rvm: 2.2.5
      env: INTEGRATION_LOG=1 INTEGRATION=1


